export default {
    Program: 'PROGRAM',
    typeSpecifier: 'TYPESPECIFIER',
    varDecl: 'VARDECL',
    funcDecl: 'FUNCDECL',
    funBody: 'FUNCBODY',
    localDeclList: 'LOCALDECLLIST',
    statementList: 'STATEMENTLIST',
    compoundStmt: 'COMPOUNDSTATEMENT',
    assignStmt: 'ASSIGNSTMT',
    expression: 'EXPRESSION',
    addExpr: 'ADD_EXPR',
    intConst: 'INTCONST',
    TYPE: 'TYPE',
    ID: 'ID',
}; 
