export default {
    Program: 'PROGRAM',
    typeSpecifier: 'TYPESPECIFIER',
    varDecl: 'VARDECL',
    funcDecl: 'FUNCDECL',
    funBody: 'FUNCBODY',
    localDeclList: 'LOCALDECLLIST',
    statementList: 'STATEMENTLIST',
    compoundStmt: 'COMPOUNDSTATEMENT',
    empty: 'EMPTY_STATEMENT',
    assignStmt: 'ASSIGNSTMT',
    expression: 'EXPRESSION',
    addExpr: 'ADD_EXPR',
    intConst: 'INTCONST',
    charConst: 'CHARCONST',
    strConst: 'STRINGCONST',
    intArray: 'INT_ARRAY',
    charArray: 'CHAR_ARRAY',
    stringArray: 'STRING_ARRAY',
    voidArray: 'VOID_ARRAY',
    arrayDecl: 'ARRAY_DECL',
    addOp: 'OPER_ADD',
    subOp: 'OPER_SUB',
    TYPE: 'TYPE',
    ID: 'ID',
}; 
